### ISSUE TITLE
Documentation for releases

### ISSUE THREAD

**Issue by skanwal** [c-BIG/NPM-sample-qc#60]
Trying to figure out the best way to test the pipeline after getting no response on a previous issue https://github.com/c-BIG/NPM-sample-qc/issues/25.

I note there was a release around September `NPM-sample-qc-0.5.1`. I have grabbed and unzipped it locally. Does it include a binary or something to build the pipeline? How am I suppose to use this release? Does this eventually also fall back to docker build approach locally?

It'll be useful if the documentation includes information on the use of release tags as well.

**Comment by mhebrard** [comment]
Hi @skanwal, 
we just released [v0.6](https://github.com/c-BIG/NPM-sample-qc/releases/tag/v0.6.0). Please have a look and follow the readme. 
I would advise to clone the repository instead of downloading the sources from zip archives.
It also required to build the docker image locally but we fixed the issue with MAcOS and tested on our end.
Conserning the use of tags, each new release come with a tag, and you can refers to it when cloning the repo or inspecting the code on github.

**Comment by skanwal** [comment]
Hi @mhebrard, 

It's still failing for me. My steps were:

```
$ git clone git@github.com:c-BIG/NPM-sample-qc.git

Cloning into 'NPM-sample-qc'...
remote: Enumerating objects: 2558, done.
remote: Counting objects: 100% (567/567), done.
remote: Compressing objects: 100% (305/305), done.
remote: Total 2558 (delta 307), reused 474 (delta 256), pack-reused 1991
Receiving objects: 100% (2558/2558), 148.05 MiB | 1.89 MiB/s, done.
Resolving deltas: 100% (1508/1508), done.
$ cd NPM-sample-qc/containers
$ sh build_npm-sample-qc_docker_image.sh
[+] Building 507.8s (14/19)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                               0.1s
 => => transferring dockerfile: 1.36kB                                                                                                                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                                                                                                                                    5.4s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                                                                                                                      0.0s
 => [ 1/14] FROM docker.io/library/ubuntu:22.04@sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca4005c2                                                                                                                                                                            5.9s
 => => resolve docker.io/library/ubuntu:22.04@sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca4005c2                                                                                                                                                                              0.0s
 => => sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca4005c2 1.42kB / 1.42kB                                                                                                                                                                                                     0.0s
 => => sha256:817cfe4672284dcbfee885b1a66094fd907630d610cab329114d036716be49ba 529B / 529B                                                                                                                                                                                                         0.0s
 => => sha256:a8780b506fa4eeb1d0779a3c92c8d5d3e6a656c758135f62826768da458b5235 1.46kB / 1.46kB                                                                                                                                                                                                     0.0s
 => => sha256:e96e057aae67380a4ddb16c337c5c3669d97fdff69ec537f02aa2cc30d814281 30.43MB / 30.43MB                                                                                                                                                                                                   3.8s
 => => extracting sha256:e96e057aae67380a4ddb16c337c5c3669d97fdff69ec537f02aa2cc30d814281                                                                                                                                                                                                          1.4s
 => [internal] load build context                                                                                                                                                                                                                                                                  0.0s
 => => transferring context: 261B                                                                                                                                                                                                                                                                  0.0s
 => [ 2/14] ADD conda_env.yml /conda_env.yml                                                                                                                                                                                                                                                       0.2s
 => [ 3/14] RUN export DEBIAN_FRONTEND="noninteractive" &&     apt-get update &&     apt-get install -y --no-install-recommends       build-essential       libtool       libarchive-dev       make cmake m4 automake       gcc g++       python3 python-pip python-dev-is-python3       git     191.4s
 => [ 4/14] RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh                                                                                                                                                                                                         8.3s
 => [ 5/14] RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/conda                                                                                                                                                                                                                     33.6s
 => [ 6/14] RUN PATH="/usr/local/conda/bin:/usr/local/conda/bin/:/usr/local/conda/envs/npm-sample-qc/share/picard-2.27.0-0/:/usr/local/conda/envs/npm-sample-qc/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"                                                                 0.2s
 => [ 7/14] RUN rm Miniconda3-latest-Linux-x86_64.sh                                                                                                                                                                                                                                               0.2s
 => [ 8/14] RUN conda update -n base -c defaults conda                                                                                                                                                                                                                                            41.9s
 => ERROR [ 9/14] RUN conda install -c conda-forge -y awscli                                                                                                                                                                                                                                     220.5s
------
 > [ 9/14] RUN conda install -c conda-forge -y awscli:
#14 2.528 Collecting package metadata (current_repodata.json): ...working... done
#14 70.95 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#14 84.62 Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
#14 106.2 Collecting package metadata (repodata.json): ...working... Killed
------
executor failed running [/bin/sh -c conda install -c conda-forge -y awscli]: exit code: 137
```

Exit code 137 suggests to me that container or pod is trying to use more memory than it's allowed.
Wondering how much does it need? 

I can try to double it in the docker preferences but it'd be nice to add this information to the README for other users as well.

**Comment by skanwal** [comment]
FYI - I increased docker memory to 4GB to build the docker image.

**Comment by mhebrard** [comment]
> FYI - I increased docker memory to 4GB to build the docker image.
Does the build worked with 4GB ?

**Comment by skanwal** [comment]
Yes, the build work. Planning to test the actual pipeline today.

**Comment by skanwal** [comment]
@mhebrard  - can you please add link to GH commit ID for documentation update, so that I can close this issue?

**Comment by mhebrard** [comment]
Solved in #61

**Comment by skanwal** [comment]
@mhebrard - don't think this is completed as the documentation hasn't been updated to include resource requirements for building docker image?

**Comment by skanwal** [comment]
Can you also please point me to a reference in the README on how to use the pipeline releases?

**Comment by mhebrard** [comment]
@skanwal - as I beleive you saw, in [v0.7](https://github.com/c-BIG/NPM-sample-qc/tree/v0.7.0) there is no more requirement to build the docker image locally, as it is pulled from docker hub.

Note that the build worked on my M1 machine with default installation of docker and fresh git clone from the v0.7. It is unclear what was the cause of the build issue you encounter in previous version.

Closing this issue.

**Comment by skanwal** [comment]
Glad to know you've taken the point on hosting the container on dockerhub.
